### ISSUE TITLE
Link broken to awsome.md

### ISSUE THREAD

**Issue by guenoledc** [thomasdarimont/awesome-keycloak#33]
Hi,

I found a broken link while preparing my merge request   
In page https://github.com/thomasdarimont/awesome-keycloak/blob/master/CONTRIBUTING.md   
the link in  
```
- Read [the awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md) and ensure your list complies.
```
 should be changed to https://github.com/sindresorhus/awesome/blob/main/awesome.md.  

The `master` branch has apparently been renamed as `main`

**Comment by JaouherK** [comment]
John oliver?

**Comment by thomasdarimont** [comment]
Fixed thanks!
